# Generated by Django 4.0 on 2021-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
