# Generated by Django 4.0 on 2021-12-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_createlisting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
