# Generated by Django 4.0 on 2022-01-04 23:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_createlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 4, 23, 18, 27, 567845, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
