# Generated by Django 4.0 on 2021-12-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_createlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='category',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.createlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.user')),
            ],
        ),
    ]
